server:
  port: 8370
datasource:
  mysql:
    url: jdbc:mysql://localhost:3306/tutorial
    className: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    dialect: org.hibernate.dialect.MySQL8Dialect
    showSql: true
    hbm2ddlAuto: update
security:
  white_list: /api/auth/register,/api/auth/login

logging.level.ROOT: INFO
logging.level.org.springframework.orm.jpa: DEBUG
logging.level.org.springframework.transaction: DEBUG
logging.level.org.hibernate.engine.transaction.internal.TransactionImpl: DEBUG